using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Banque
{
    ///////////////////////////////////////////////////////////
    //  Banque.cs
    //  Implementation of the Class Banque
    //  Generated by Enterprise Architect
    //  Created on:      27-juin-2023 16:41:25
    //  Original author: TBonhommebrenner
    ///////////////////////////////////////////////////////////

    public class Banque
    {
        private string nom;
        private string ville;
        public List<Compte> mesComptes;

        public Banque()
        {

        }

        /// 
        /// <param name="_ville"></param>
        /// <param name="_nom"></param>
        public Banque(string _ville, string _nom)
        {

        }

        /// 
        /// <param name="unCompte"></param>
        private void AjouteCompte(Compte unCompte)
        {

        }

        /// 
        /// <param name="_decouvertAutorise"></param>
        /// <param name="_solde"></param>
        /// <param name="_nom"></param>
        /// <param name="_num"></param>
        public void AjouteCompte(int _decouvertAutorise, int _solde, string _nom, int _num)
        {

        }

    }//end Banque
}
