namespace Banque
{
    ///////////////////////////////////////////////////////////
    //  Banque.cs
    //  Implementation of the Class Banque
    //  Generated by Enterprise Architect
    //  Created on:      27-juin-2023 16:41:25
    //  Original author: TBonhommebrenner
    ///////////////////////////////////////////////////////////

    public class Banque
    {
        private string nom;
        private string ville;
        private List<Compte> mesComptes;

        public Banque()
        {
            nom = "";
            ville = "";
            mesComptes = new List<Compte>();
        }

        ///         
        /// <param name="_nom"></param>
        /// <param name="_ville"></param>
        public Banque(string _nom, string _ville)
        {
            nom = _nom;
            ville = _ville;
            mesComptes = new List<Compte>();
        }

        /// 
        /// <param name="_unCompte"></param>
        private void AjouteCompte(Compte _unCompte)
        {
            mesComptes.Add(_unCompte);
        }

        /// 
        /// <param name="_decouvertAutorise"></param>
        /// <param name="_solde"></param>
        /// <param name="_nom"></param>
        /// <param name="_num"></param>
        public void AjouteCompte(int _num, string _nom, double _solde, double _decouvertAutorise)
        {
            mesComptes.Add(new Compte(_num, _nom, _solde, _decouvertAutorise));
        }

        public Compte CompteSup()
        {
            Compte compteAvecSoldeMax = mesComptes.ElementAt(0);

            foreach (Compte compte in mesComptes)
            {
                if(compte.Solde > compteAvecSoldeMax.Solde)
                {
                    compteAvecSoldeMax = compte;
                }
            }

            return compteAvecSoldeMax;
        }

        public Compte? RendCompte(int _numero)
        {
            foreach (Compte compte in mesComptes)
            {
                if (compte.Numero == _numero)
                {
                    return compte;
                }
            }

            return null;
        }

        public override string ToString()
        {
            string str = "nom : " + nom + "\nville : " + ville + "\nmes comptes : ";

            foreach(Compte compte in mesComptes)
            {
                str += "\n" + compte.ToString();
            }

            str += "\n---";

            return str;
        }
    }//end Banque
}
