using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Banque
{
    ///////////////////////////////////////////////////////////
    //  Compte.cs
    //  Implementation of the Class Compte
    //  Generated by Enterprise Architect
    //  Created on:      27-juin-2023 16:41:22
    //  Original author: TBonhommebrenner
    ///////////////////////////////////////////////////////////

    public class Compte
    {
        private double decouvertAutorise;
        private string nom;
        private int numero;
        private double solde;

        public Compte()
        {

        }

        /// 
        /// <param name="_decouvertAutorise"></param>
        /// <param name="_solde"></param>
        /// <param name="_nom"></param>
        /// <param name="_numero"></param>
        public Compte(double _decouvertAutorise, int _solde, string _nom, int _numero)
        {

        }

        public Compte CompteSup()
        {

            return null;
        }

        /// 
        /// <param name="_montant"></param>
        public void Crediter(double _montant)
        {

        }

        /// 
        /// <param name="_montant"></param>
        public bool Debiter(double _montant)
        {

            return false;
        }

        public int GetNumero()
        {

            return 0;
        }

        public void RendCompte()
        {

        }

        /// 
        /// <param name="_autreCompte"></param>
        public void Superieur(Compte _autreCompte)
        {

        }

        public string ToString()
        {

            return "";
        }

        /// 
        /// <param name="_compteDestinataire"></param>
        /// <param name="_montant"></param>
        public bool Transferer(Compte _compteDestinataire, int _montant)
        {

            return false;
        }

    }//end Compte
}
